### ISSUE TITLE
Are we (I) missing a string library?

### ISSUE THREAD

**Issue by mashcode** [EricSchles/scraping_grownyc#1]
scraper.py:15: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  tmp.append(unidecode(row.text_content().replace("\n","").replace("\t","")))

**Comment by EricSchles** [comment]
This is just a warning - the file is still generated. : - )

**Comment by mashcode** [comment]
Yes sir! See you tomorrow 

(917) 570-7079 @mashcode @compostandco
